// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAejj4ivS5JnJJwMTKNbEQDAWfUuaOXslc',
    appId: '1:31768369064:web:c0267d1521fa33d5d6af9d',
    messagingSenderId: '31768369064',
    projectId: 'university-companion-279b3',
    authDomain: 'university-companion-279b3.firebaseapp.com',
    storageBucket: 'university-companion-279b3.firebasestorage.app',
    measurementId: 'G-YP804FWQX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwG5XjKBGBQdGgNJcOOPveFKvZyOkl6tg',
    appId: '1:31768369064:android:1d4d213ca3eb4bb6d6af9d',
    messagingSenderId: '31768369064',
    projectId: 'university-companion-279b3',
    storageBucket: 'university-companion-279b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEPMKDUixmx_IfbDIMJICpxKhwV4wPbRo',
    appId: '1:31768369064:ios:f070af25d45f99dbd6af9d',
    messagingSenderId: '31768369064',
    projectId: 'university-companion-279b3',
    storageBucket: 'university-companion-279b3.firebasestorage.app',
    iosBundleId: 'com.example.universityCompanionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEPMKDUixmx_IfbDIMJICpxKhwV4wPbRo',
    appId: '1:31768369064:ios:f070af25d45f99dbd6af9d',
    messagingSenderId: '31768369064',
    projectId: 'university-companion-279b3',
    storageBucket: 'university-companion-279b3.firebasestorage.app',
    iosBundleId: 'com.example.universityCompanionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAejj4ivS5JnJJwMTKNbEQDAWfUuaOXslc',
    appId: '1:31768369064:web:6550e47292ae7284d6af9d',
    messagingSenderId: '31768369064',
    projectId: 'university-companion-279b3',
    authDomain: 'university-companion-279b3.firebaseapp.com',
    storageBucket: 'university-companion-279b3.firebasestorage.app',
    measurementId: 'G-4FZBSH70HW',
  );
}
